version: '2'
services:
  webapp:
    image: ensimag/fablab_project:1
    ports:
      - "80:3000"
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
  mongodb:
    image: ensimag/rpi_mongo:1
