version: '2'
services:
  webapp:
    container_name: fablab
    image: fablab/rpi_webapp:1
    environment:
      - MODE=PROD
    ports:
      - "80:3000"
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
  mongodb:
    container_name: mongodb
    image: fablab/rpi_mongo:1
    ports:
      - "27017:27017"
    volumes:
      - ../mongodb_image/db:/data/db
